## Workflow for Neosurf-on-Neosurf MaSIF search

In [25]:
import os
import pandas as pd

repo_root = !git rev-parse --show-toplevel
repo_root = repo_root[0]
os.chdir(repo_root)

# ----- Directories ------
data_dir = os.path.join(repo_root, 'data')

# ----- Input ------
# .csv about the seed complexes
seed_list_csv = os.path.join(data_dir, 'nico_targets.csv')

# Directory to store input .pdb and .sdf
input_dir = os.path.join(data_dir, 'input')
os.makedirs(input_dir, exist_ok=True)
input_manifest = os.path.join(input_dir, 'input_manifest.csv')

# ----- Output ------
# Directory to write preprocessing files
preprocess_dir = os.path.join(data_dir, 'preprocess')

# Directory to write masif-search output
masif_search_out_dir = os.path.join(data_dir, 'masif_search')
os.makedirs(masif_search_out_dir, exist_ok=True)

___
### Step 1 - preprocess all targets
1. Preprocess targets with ligands in nico_targets.csv
2. Preprocess VHL and CRBN with ligands

In [3]:
df_seed = pd.read_csv(seed_list_csv)

df_seed.head()

,uniprot_id,gene_name,recommendedName,pdb_id,protein_chain,ligand_chain,ligand_code,ligand_name,smiles,percent_intracellular,formula,mw,qed,num_carbon,num_N_O,uniprot_id_count
0,P35222,CTNNB1,Catenin beta-1,6M90,C,A,J91,2-(2-fluorophenoxy)-3-{[2-oxo-6-(trifluorometh...,c1ccc(c(c1)Oc2c(cccc2NC(=O)C3=CC=C(NC3=O)C(F)(...,1.0,C20H12F4N2O5,436.068234,0.517802,20.0,7.0,1.0
1,P35222,CTNNB1,Catenin beta-1,6M91,C,A,J97,"3-({4-[(2,6-dichlorophenyl)sulfanyl]-2-oxo-6-(...",c1cc(cc(c1)NC(=O)C2=C(C=C(NC2=O)C(F)(F)F)Sc3c(...,1.0,C20H11Cl2F3N2O4S,501.976868,0.408829,20.0,6.0,1.0
2,P35222,CTNNB1,Catenin beta-1,6M92,C,A,J8V,"3-{[2-oxo-4-phenoxy-6-(trifluoromethyl)-1,2-di...",c1ccc(cc1)OC2=C(C(=O)NC(=C2)C(F)(F)F)C(=O)Nc3c...,1.0,C20H13F3N2O5,418.077656,0.577285,20.0,7.0,1.0
3,P35222,CTNNB1,Catenin beta-1,6M93,C,A,J8Y,2-oxo-N-[3-(1H-tetrazol-5-yl)phenyl]-6-(triflu...,c1cc(cc(c1)NC(=O)C2=CC=C(NC2=O)C(F)(F)F)c3[nH]...,1.0,C14H9F3N6O2,350.073908,0.666230,14.0,8.0,1.0
4,P35222,CTNNB1,Catenin beta-1,7AFW,A,A,R9Q,"3-[(2~{R})-4-methyl-5-oxidanylidene-2,3-dihydr...",CN1C[C@H](Oc2ccccc2C1=O)c3cccc(c3)C#N,1.0,C17H14N2O2,278.105528,0.805631,17.0,4.0,1.0

In [9]:
# ----- Helper functions for preparing preprocessing inputs ------
#
# prepare_input_structures() orchestrates one row of df_seed (nico_targets.csv) into
# MaSIF-ready files under input_dir. Per complex the workflow is:
#
#   1. Download the full PDB from RCSB and the ligand SDF (models.rcsb.org) into
#      input_dir / a temp directory.
#   2. Trim the structure to the target protein (standard amino acids on protein_chain)
#      plus a single ligand residue (ligand_code on ligand_chain). If protein_chain
#      and ligand_chain are the same, both are kept on that chain.
#   3. Build a target name {pdb_id}_{chains}, where chains = protein_chain + ligand_chain
#      deduplicated (e.g. C+A -> CA, A+A -> A).
#   4. EvoEF2 RepairStructure on a protein-only PDB (ligand stripped); repaired
#      coordinates are written to a temp file as structure_Repair.pdb.
#   5. Merge the original ligand HETATM/ATOM records from the pre-repair trimmed complex
#      onto the repaired protein and save the final PDB to input_dir.
#   6. Return a dict for df_preprocess: pdb_path, target, ligand ({code}_{chain}),
#      ligand_path ({pdb_id}_{protein_chain}_{ligand_code}.sdf).
#
# Files are always rebuilt (no skip-if-exists). The driver cell loops df_seed and
# calls prepare_input_structures(row, input_dir, repo_root/EvoEF2/EvoEF2).

import shutil
import subprocess
import tempfile
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import urlopen

from Bio.PDB import PDBIO, PDBParser, Select

# chains suffix: protein_chain + ligand_chain, deduplicated (C+A -> CA, A+A -> A)
STANDARD_AA = {
    "ALA", "ARG", "ASN", "ASP", "CYS", "GLN", "GLU", "GLY", "HIS", "ILE",
    "LEU", "LYS", "MET", "PHE", "PRO", "SER", "THR", "TRP", "TYR", "VAL",
    "MSE",
}

evoef2_bin = os.path.join(repo_root, "EvoEF2", "EvoEF2")

def chain_suffix(protein_chain, ligand_chain):
    if protein_chain == ligand_chain:
        return protein_chain
    return protein_chain + ligand_chain


def _is_standard_protein_residue(residue):
    return residue.id[0] == " " and residue.get_resname().strip() in STANDARD_AA


def _is_ligand_residue(residue, ligand_code):
    return residue.get_resname().strip() == ligand_code.strip()


class _ComplexSelect(Select):
    def __init__(self, protein_chain, ligand_chain, ligand_code):
        self.protein_chain = protein_chain
        self.ligand_chain = ligand_chain
        self.ligand_code = ligand_code
        self._chains = {protein_chain, ligand_chain}

    def accept_chain(self, chain):
        return chain.id in self._chains

    def accept_residue(self, residue):
        chain_id = residue.parent.id
        if chain_id == self.protein_chain:
            if self.protein_chain == self.ligand_chain:
                return _is_standard_protein_residue(residue) or _is_ligand_residue(
                    residue, self.ligand_code
                )
            return _is_standard_protein_residue(residue)
        if chain_id == self.ligand_chain:
            return _is_ligand_residue(residue, self.ligand_code)
        return False


class _ProteinOnlySelect(Select):
    def __init__(self, protein_chain):
        self.protein_chain = protein_chain

    def accept_chain(self, chain):
        return chain.id == self.protein_chain

    def accept_residue(self, residue):
        return _is_standard_protein_residue(residue)


def _download_url(url, dest_path):
    dest_path = Path(dest_path)
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with urlopen(url) as response:
            dest_path.write_bytes(response.read())
    except HTTPError as exc:
        raise RuntimeError(f"Download failed ({exc.code}): {url}") from exc


def download_pdb(pdb_id, dest_path):
    url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
    _download_url(url, dest_path)


def download_ligand_sdf(pdb_id, ligand_chain, dest_path):
    url = (
        f"https://models.rcsb.org/v1/{pdb_id}/ligand"
        f"?label_asym_id={ligand_chain}&encoding=sdf"
    )
    _download_url(url, dest_path)


def _extract_ligand_pdb_lines(pdb_path, ligand_chain, ligand_code):
    lines = []
    with open(pdb_path) as handle:
        for line in handle:
            if not (line.startswith("HETATM") or line.startswith("ATOM")):
                continue
            if line[21] != ligand_chain:
                continue
            if line[17:20].strip() != ligand_code.strip():
                continue
            lines.append(line)
    if not lines:
        raise ValueError(
            f"No ligand records for resname={ligand_code} chain={ligand_chain} in {pdb_path}"
        )
    return lines


def _merge_repaired_protein_with_ligand(repaired_pdb, trimmed_pdb, ligand_chain, ligand_code, output_pdb):
    ligand_lines = _extract_ligand_pdb_lines(trimmed_pdb, ligand_chain, ligand_code)
    out_lines = []
    with open(repaired_pdb) as handle:
        for line in handle:
            if line.startswith("END"):
                break
            if line.strip():
                out_lines.append(line)
    out_lines.extend(ligand_lines)
    out_lines.append("END\n")
    Path(output_pdb).write_text("".join(out_lines))


def evoef2_repair_structure(input_pdb, output_pdb, evoef2_bin):
    """Run EvoEF2 RepairStructure; intermediate {stem}_Repair.pdb lives in a temp directory."""
    evoef2_bin = str(evoef2_bin)
    if not os.path.isfile(evoef2_bin):
        raise FileNotFoundError(
            f"EvoEF2 binary not found at {evoef2_bin}. Build with: cd EvoEF2 && ./build.sh"
        )
    output_pdb = Path(output_pdb)
    output_pdb.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        stem = "structure"
        work_pdb = tmp / f"{stem}.pdb"
        shutil.copy2(input_pdb, work_pdb)
        subprocess.run(
            [
                evoef2_bin,
                "--command=RepairStructure",
                f"--pdb={stem}.pdb"
            ],
            cwd=tmp,
            check=True,
        )
        repaired = tmp / f"{stem}_Repair.pdb"
        if not repaired.is_file():
            raise FileNotFoundError(f"EvoEF2 did not create {repaired}")
        shutil.copy2(repaired, output_pdb)


def prepare_input_structures(pdb_id, protein_chain, ligand_chain, ligand_code, input_dir, evoef2_bin):
    """
    Download PDB/SDF, trim to protein+ligand, EvoEF2-repair protein, merge ligand, write to input_dir.

    chains suffix: protein_chain + ligand_chain (deduplicated if equal).
    """
    input_dir = Path(input_dir)

    chains = chain_suffix(protein_chain, ligand_chain)
    target = f"{pdb_id}_{chains}"
    ligand_name = f"{ligand_code}_{ligand_chain}"
    pdb_path = input_dir / f"{target}.pdb"
    ligand_path = input_dir / f"{pdb_id}_{protein_chain}_{ligand_code}.sdf"

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        full_pdb = tmp / f"{pdb_id}.pdb"
        download_pdb(pdb_id, full_pdb)
        download_ligand_sdf(pdb_id, ligand_chain, ligand_path)

        parser = PDBParser(QUIET=True)
        structure = parser.get_structure(pdb_id, str(full_pdb))

        trimmed_pdb = tmp / "trimmed.pdb"
        pdb_io = PDBIO()
        pdb_io.set_structure(structure)
        pdb_io.save(str(trimmed_pdb), _ComplexSelect(protein_chain, ligand_chain, ligand_code))
        _extract_ligand_pdb_lines(trimmed_pdb, ligand_chain, ligand_code)

        protein_only_pdb = tmp / "protein_only.pdb"
        pdb_io.set_structure(structure)
        pdb_io.save(str(protein_only_pdb), _ProteinOnlySelect(protein_chain))

        repaired_protein_pdb = tmp / "repaired_protein.pdb"
        evoef2_repair_structure(
            protein_only_pdb, repaired_protein_pdb, evoef2_bin
        )
        _merge_repaired_protein_with_ligand(
            repaired_protein_pdb, trimmed_pdb, ligand_chain, ligand_code, pdb_path
        )

    return {
        "pdb_path": str(pdb_path.resolve()),
        "target": target,
        "ligand": ligand_name,
        "ligand_path": str(ligand_path.resolve()),
    }

In [ ]:
# Iterate over all rows in df_seed

rows = []
for _, row in df_seed.iterrows():
    print(f"Preparing {row['pdb_id']} ({row['protein_chain']} + {row['ligand_chain']})...")
    pdb_id = row["pdb_id"]
    protein_chain = row["protein_chain"]
    ligand_chain = row["ligand_chain"]
    ligand_code = row["ligand_code"]
    rows.append(prepare_input_structures(pdb_id, protein_chain, ligand_chain, ligand_code, input_dir, evoef2_bin))

df_preprocess = pd.DataFrame(rows)
df_preprocess

Preparing 6M90 (C + A)...
############################################################################################
                                    EvoEF2
  A framework for macromolecular modeling, e.g.,protein design, protein side-chain packing,
protein structure energy minimization, add and optimize hydrogen bonds, build mutant model,
calculate protein folding stability, calculate protein-protein binding free energy, etc


  Copyright (c) Xiaoqiang Huang (xiaoqiah@umich.edu; tommyhuangthu@foxmail.com)
  Dept. of Computational Medicine & Bioinformatics
  Medical School
  University of Michigan
############################################################################################
command RepairStructure works
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue C31LEU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD1 on residue C31LEU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD2 on residue C31LEU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OG1 on residue C40THR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG2 on residue C40THR is invalid
EvoEF Repairing PDB: optimization cycle 1 ...
We optimize side chain of residue C31L
We optimize side chain of residue C32D
We optimize side chain of residue C35I
We will flip residue C36H to optimize hbond
We optimize side chain of residue C36H
We will rotate hydroxyl group of residue C37S to optimize hbond
We optimize side chain of residue C37S
We will rotate hydroxyl group of residue C40T to optimize hbond
We optimize side chain of residue C40T
Time spent: 0.276470
Preparing 6M91 (C + A)...
############################################################################################
                                    EvoEF2
  A framework for macromolecular modeling, e.g.,protein design, protein side-chain packing,
protein structure energy minimization, add and optimize hydrogen bonds, build mutant model,
calculate protein folding stability, calculate protein-protein binding free energy, etc


  Copyright (c) Xiaoqiang Huang (xiaoqiah@umich.edu; tommyhuangthu@foxmail.com)
  Dept. of Computational Medicine & Bioinformatics
  Medical School
  University of Michigan
############################################################################################
command RepairStructure works
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OG on residue C29SER is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD1 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD2 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CE1 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CE2 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CZ on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OH on residue C30TYR is invalid
EvoEF Repairing PDB: optimization cycle 1 ...
We will rotate hydroxyl group of residue C29S to optimize hbond
We optimize side chain of residue C29S
We will rotate hydroxyl group of residue C30Y to optimize hbond
We optimize side chain of residue C30Y
We optimize side chain of residue C31L
We optimize side chain of residue C32D
We optimize side chain of residue C35I
We will flip residue C36H to optimize hbond
We optimize side chain of residue C36H
Time spent: 0.278045
Preparing 6M92 (C + A)...
############################################################################################
                                    EvoEF2
  A framework for macromolecular modeling, e.g.,protein design, protein side-chain packing,
protein structure energy minimization, add and optimize hydrogen bonds, build mutant model,
calculate protein folding stability, calculate protein-protein binding free energy, etc


  Copyright (c) Xiaoqiang Huang (xiaoqiah@umich.edu; tommyhuangthu@foxmail.com)
  Dept. of Computational Medicine & Bioinformatics
  Medical School
  University of Michigan
############################################################################################
command RepairStructure works
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD1 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD2 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CE1 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CE2 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CZ on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OH on residue C30TYR is invalid
EvoEF Repairing PDB: optimization cycle 1 ...
We will rotate hydroxyl group of residue C30Y to optimize hbond
We optimize side chain of residue C30Y
We optimize side chain of residue C31L
We optimize side chain of residue C32D
We optimize side chain of residue C35I
We will flip residue C36H to optimize hbond
We optimize side chain of residue C36H
We will rotate hydroxyl group of residue C37S to optimize hbond
We optimize side chain of residue C37S
Time spent: 0.278512
Preparing 6M93 (C + A)...
############################################################################################
                                    EvoEF2
  A framework for macromolecular modeling, e.g.,protein design, protein side-chain packing,
protein structure energy minimization, add and optimize hydrogen bonds, build mutant model,
calculate protein folding stability, calculate protein-protein binding free energy, etc


  Copyright (c) Xiaoqiang Huang (xiaoqiah@umich.edu; tommyhuangthu@foxmail.com)
  Dept. of Computational Medicine & Bioinformatics
  Medical School
  University of Michigan
############################################################################################
command RepairStructure works
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD1 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD2 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CE1 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CE2 on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CZ on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OH on residue C30TYR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OG1 on residue C40THR is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG2 on residue C40THR is invalid
EvoEF Repairing PDB: optimization cycle 1 ...
We will rotate hydroxyl group of residue C30Y to optimize hbond
We optimize side chain of residue C30Y
We optimize side chain of residue C31L
We optimize side chain of residue C32D
We optimize side chain of residue C35I
We will flip residue C36H to optimize hbond
We optimize side chain of residue C36H
We will rotate hydroxyl group of residue C37S to optimize hbond
We optimize side chain of residue C37S
We will rotate hydroxyl group of residue C40T to optimize hbond
We optimize side chain of residue C40T
Time spent: 0.277186
Preparing 7AFW (A + A)...
############################################################################################
                                    EvoEF2
  A framework for macromolecular modeling, e.g.,protein design, protein side-chain packing,
protein structure energy minimization, add and optimize hydrogen bonds, build mutant model,
calculate protein folding stability, calculate protein-protein binding free energy, etc


  Copyright (c) Xiaoqiang Huang (xiaoqiah@umich.edu; tommyhuangthu@foxmail.com)
  Dept. of Computational Medicine & Bioinformatics
  Medical School
  University of Michigan
############################################################################################
command RepairStructure works
EvoEF Repairing PDB: optimization cycle 1 ...
We optimize side chain of residue A144D
We optimize side chain of residue A145D
We optimize side chain of residue A147E
We optimize side chain of residue A148L
We will rotate hydroxyl group of residue A150T to optimize hbond
We optimize side chain of residue A150T
We optimize side chain of residue A151R
We optimize side chain of residue A153I
We optimize side chain of residue A154P
We optimize side chain of residue A155E
We optimize side chain of residue A156L
We will rotate hydroxyl group of residue A157T to optimize hbond
We optimize side chain of residue A157T
We optimize side chain of residue A158K
We optimize side chain of residue A159L
We optimize side chain of residue A160L
We will flip residue A161N to optimize hbond
We optimize side chain of residue A161N
We optimize side chain of residue A162D
We optimize side chain of residue A163E
We optimize side chain of residue A164D
We will flip residue A165Q to optimize hbond
We optimize side chain of residue A165Q
We optimize side chain of residue A166V
We optimize side chain of residue A167V
We optimize side chain of residue A168V
We will flip residue A169N to optimize hbond
We optimize side chain of residue A169N
We optimize side chain of residue A170K
We optimize side chain of residue A173V
We optimize side chain of residue A174M
We optimize side chain of residue A175V
We will flip residue A176H to optimize hbond
We optimize side chain of residue A176H
We will flip residue A177Q to optimize hbond
We optimize side chain of residue A177Q
We optimize side chain of residue A178L
We will rotate hydroxyl group of residue A179S to optimize hbond
We optimize side chain of residue A179S
We optimize side chain of residue A180K
We optimize side chain of residue A181K
We optimize side chain of residue A182E
We will rotate hydroxyl group of residue A184S to optimize hbond
We optimize side chain of residue A184S
We optimize side chain of residue A185R
We will flip residue A186H to optimize hbond
We optimize side chain of residue A186H
We optimize side chain of residue A188I
We optimize side chain of residue A189M
We optimize side chain of residue A190R
We will rotate hydroxyl group of residue A191S to optimize hbond
We optimize side chain of residue A191S
We optimize side chain of residue A192P
We will flip residue A193Q to optimize hbond
We optimize side chain of residue A193Q
We optimize side chain of residue A194M
We optimize side chain of residue A195V
We will rotate hydroxyl group of residue A196S to optimize hbond
We optimize side chain of residue A196S
We optimize side chain of residue A198I
We optimize side chain of residue A199V
We optimize side chain of residue A200R
We will rotate hydroxyl group of residue A201T to optimize hbond
We optimize side chain of residue A201T
We optimize side chain of residue A202M
We will flip residue A203Q to optimize hbond
We optimize side chain of residue A203Q
We will flip residue A204N to optimize hbond
We optimize side chain of residue A204N
We will rotate hydroxyl group of residue A205T to optimize hbond
We optimize side chain of residue A205T
We will flip residue A206N to optimize hbond
We optimize side chain of residue A206N
We optimize side chain of residue A207D
We optimize side chain of residue A208V
We optimize side chain of residue A209E
We will rotate hydroxyl group of residue A210T to optimize hbond
We optimize side chain of residue A210T
We optimize side chain of residue A212R
We will rotate hydroxyl group of residue A214T to optimize hbond
We optimize side chain of residue A214T
We will rotate hydroxyl group of residue A217T to optimize hbond
We optimize side chain of residue A217T
We optimize side chain of residue A218L
We will flip residue A219H to optimize hbond
We optimize side chain of residue A219H
We will flip residue A220N to optimize hbond
We optimize side chain of residue A220N
We optimize side chain of residue A221L
We will rotate hydroxyl group of residue A222S to optimize hbond
We optimize side chain of residue A222S
We will flip residue A223H to optimize hbond
We optimize side chain of residue A223H
We will flip residue A224H to optimize hbond
We optimize side chain of residue A224H
We optimize side chain of residue A225R
We optimize side chain of residue A226E
We optimize side chain of residue A228L
We optimize side chain of residue A229L
We optimize side chain of residue A231I
We optimize side chain of residue A232F
We optimize side chain of residue A233K
We will rotate hydroxyl group of residue A234S to optimize hbond
We optimize side chain of residue A234S
We optimize side chain of residue A237I
We optimize side chain of residue A238P
We optimize side chain of residue A240L
We optimize side chain of residue A241V
We optimize side chain of residue A242K
We optimize side chain of residue A243M
We optimize side chain of residue A244L
We will rotate hydroxyl group of residue A246S to optimize hbond
We optimize side chain of residue A246S
We optimize side chain of residue A247P
We optimize side chain of residue A248V
We optimize side chain of residue A249D
We will rotate hydroxyl group of residue A250S to optimize hbond
We optimize side chain of residue A250S
We optimize side chain of residue A251V
We optimize side chain of residue A252L
We optimize side chain of residue A253F
We will rotate hydroxyl group of residue A254Y to optimize hbond
We optimize side chain of residue A254Y
We optimize side chain of residue A256I
We will rotate hydroxyl group of residue A257T to optimize hbond
We optimize side chain of residue A257T
We will rotate hydroxyl group of residue A258T to optimize hbond
We optimize side chain of residue A258T
We optimize side chain of residue A259L
We will flip residue A260H to optimize hbond
We optimize side chain of residue A260H
We will flip residue A261N to optimize hbond
We optimize side chain of residue A261N
We optimize side chain of residue A262L
We optimize side chain of residue A263L
We optimize side chain of residue A264L
We will flip residue A265H to optimize hbond
We optimize side chain of residue A265H
We will flip residue A266Q to optimize hbond
We optimize side chain of residue A266Q
We optimize side chain of residue A267E
We optimize side chain of residue A270K
We optimize side chain of residue A271M
We optimize side chain of residue A273V
We optimize side chain of residue A274R
We optimize side chain of residue A275L
We optimize side chain of residue A279L
We will flip residue A280Q to optimize hbond
We optimize side chain of residue A280Q
We optimize side chain of residue A281K
We optimize side chain of residue A282M
We optimize side chain of residue A283V
We optimize side chain of residue A285L
We optimize side chain of residue A286L
We will flip residue A287N to optimize hbond
We optimize side chain of residue A287N
We optimize side chain of residue A288K
We will rotate hydroxyl group of residue A289T to optimize hbond
We optimize side chain of residue A289T
We will flip residue A290N to optimize hbond
We optimize side chain of residue A290N
We optimize side chain of residue A291V
We optimize side chain of residue A292K
We optimize side chain of residue A293F
We optimize side chain of residue A294L
We optimize side chain of residue A296I
We will rotate hydroxyl group of residue A297T to optimize hbond
We optimize side chain of residue A297T
We will rotate hydroxyl group of residue A298T to optimize hbond
We optimize side chain of residue A298T
We optimize side chain of residue A299D
We optimize side chain of residue A301L
We will flip residue A302Q to optimize hbond
We optimize side chain of residue A302Q
We optimize side chain of residue A303I
We optimize side chain of residue A304L
Time spent: 0.350259
Preparing 7UWO (A + B)...
############################################################################################
                                    EvoEF2
  A framework for macromolecular modeling, e.g.,protein design, protein side-chain packing,
protein structure energy minimization, add and optimize hydrogen bonds, build mutant model,
calculate protein folding stability, calculate protein-protein binding free energy, etc


  Copyright (c) Xiaoqiang Huang (xiaoqiah@umich.edu; tommyhuangthu@foxmail.com)
  Dept. of Computational Medicine & Bioinformatics
  Medical School
  University of Michigan
############################################################################################
command RepairStructure works
EvoEF Repairing PDB: optimization cycle 1 ...
We optimize side chain of residue A153I
We optimize side chain of residue A154P
We optimize side chain of residue A155E
We optimize side chain of residue A156L
We will rotate hydroxyl group of residue A157T to optimize hbond
We optimize side chain of residue A157T
We optimize side chain of residue A158K
We optimize side chain of residue A159L
We optimize side chain of residue A160L
We will flip residue A161N to optimize hbond
We optimize side chain of residue A161N
We optimize side chain of residue A162D
We optimize side chain of residue A163E
We optimize side chain of residue A164D
We will flip residue A165Q to optimize hbond
We optimize side chain of residue A165Q
We optimize side chain of residue A166V
We optimize side chain of residue A167V
We optimize side chain of residue A168V
We will flip residue A169N to optimize hbond
We optimize side chain of residue A169N
We optimize side chain of residue A170K
We optimize side chain of residue A173V
We optimize side chain of residue A174M
We optimize side chain of residue A175V
We will flip residue A176H to optimize hbond
We optimize side chain of residue A176H
We will flip residue A177Q to optimize hbond
We optimize side chain of residue A177Q
We optimize side chain of residue A178L
We will rotate hydroxyl group of residue A179S to optimize hbond
We optimize side chain of residue A179S
We optimize side chain of residue A180K

,pdb_path,target,ligand,ligand_path
0,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M90_CA,J91_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
1,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M91_CA,J97_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
2,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M92_CA,J8V_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
3,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M93_CA,J8Y_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
4,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,7AFW_A,R9Q_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
5,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,7UWO_AB,WHL_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
6,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,7ZRB_A,JKI_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
7,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EI9_C,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
8,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EIA_AC,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
9,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EIB_AC,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
10,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EIC_AC,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
11,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8RU4_A,GLC_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
12,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSM_A,O2D_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
13,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSN_B,O2J_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
14,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSO_A,O2M_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
15,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSP_A,LVV_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
16,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSQ_B,HR5_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
17,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSR_B,NU4_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
18,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSS_A,O2P_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
19,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QST_AC,O3A_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
20,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSU_AC,O3D_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
21,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSV_D,O3G_D,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
22,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSW_AC,O3J_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
23,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSX_CB,O3M_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
24,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSY_B,K0J_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
25,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSZ_A,K3J_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...

In [10]:
# Add VHL structure as well:
pdb_id = "8VLB"
protein_chain = "A"
ligand_chain = "A"
ligand_code = "3JF"


rows.append(prepare_input_structures(pdb_id, protein_chain, ligand_chain, ligand_code, input_dir, evoef2_bin))

df_preprocess = pd.DataFrame(rows)
df_preprocess

############################################################################################
                                    EvoEF2
  A framework for macromolecular modeling, e.g.,protein design, protein side-chain packing,
protein structure energy minimization, add and optimize hydrogen bonds, build mutant model,
calculate protein folding stability, calculate protein-protein binding free energy, etc


  Copyright (c) Xiaoqiang Huang (xiaoqiah@umich.edu; tommyhuangthu@foxmail.com)
  Dept. of Computational Medicine & Bioinformatics
  Medical School
  University of Michigan
############################################################################################
command RepairStructure works
EvoEF Repairing PDB: optimization cycle 1 ...
We optimize side chain of residue A61P
We optimize side chain of residue A62V
We optimize side chain of residue A63L
We optimize side chain of residue A64R
We will rotate hydroxyl group of residue A65S to optimize hbond
We optimize side chain of residue A65S
We optimize side chain of residue A66V
We will flip residue A67N to optimize hbond
We optimize side chain of residue A67N
We will rotate hydroxyl group of residue A68S to optimize hbond
We optimize side chain of residue A68S
We optimize side chain of residue A69R
We optimize side chain of residue A70E
We optimize side chain of residue A71P
We will rotate hydroxyl group of residue A72S to optimize hbond
We optimize side chain of residue A72S
We will flip residue A73Q to optimize hbond
We optimize side chain of residue A73Q
We optimize side chain of residue A74V
We optimize side chain of residue A75I
We optimize side chain of residue A76F
We will flip residue A78N to optimize hbond
We optimize side chain of residue A78N
We optimize side chain of residue A79R
We will rotate hydroxyl group of residue A80S to optimize hbond
We optimize side chain of residue A80S
We optimize side chain of residue A81P
We optimize side chain of residue A82R
We optimize side chain of residue A83V
We optimize side chain of residue A84V
We optimize side chain of residue A85L
We optimize side chain of residue A86P
We optimize side chain of residue A87V
We optimize side chain of residue A88W
We optimize side chain of residue A89L
We will flip residue A90N to optimize hbond
We optimize side chain of residue A90N
We optimize side chain of residue A91F
We optimize side chain of residue A92D
We optimize side chain of residue A94E
We optimize side chain of residue A95P
We will flip residue A96Q to optimize hbond
We optimize side chain of residue A96Q
We optimize side chain of residue A97P
We will rotate hydroxyl group of residue A98Y to optimize hbond
We optimize side chain of residue A98Y
We optimize side chain of residue A99P
We will rotate hydroxyl group of residue A100T to optimize hbond
We optimize side chain of residue A100T
We optimize side chain of residue A101L
We optimize side chain of residue A102P
We optimize side chain of residue A103P
We will rotate hydroxyl group of residue A105T to optimize hbond
We optimize side chain of residue A105T
We optimize side chain of residue A107R
We optimize side chain of residue A108R
We optimize side chain of residue A109I
We will flip residue A110H to optimize hbond
We optimize side chain of residue A110H
We will rotate hydroxyl group of residue A111S to optimize hbond
We optimize side chain of residue A111S
We will rotate hydroxyl group of residue A112Y to optimize hbond
We optimize side chain of residue A112Y
We optimize side chain of residue A113R
We will flip residue A115H to optimize hbond
We optimize side chain of residue A115H
We optimize side chain of residue A116L
We optimize side chain of residue A117W
We optimize side chain of residue A118L
We optimize side chain of residue A119F
We optimize side chain of residue A120R
We optimize side chain of residue A121D
We will rotate hydroxyl group of residue A124T to optimize hbond
We optimize side chain of residue A124T
We will flip residue A125H to optimize hbond
We optimize side chain of residue A125H
We optimize side chain of residue A126D
We optimize side chain of residue A128L
We optimize side chain of residue A129L
We optimize side chain of residue A130V
We will flip residue A131N to optimize hbond
We optimize side chain of residue A131N
We will flip residue A132Q to optimize hbond
We optimize side chain of residue A132Q
We will rotate hydroxyl group of residue A133T to optimize hbond
We optimize side chain of residue A133T
We optimize side chain of residue A134E
We optimize side chain of residue A135L
We optimize side chain of residue A136F
We optimize side chain of residue A137V
We optimize side chain of residue A138P
We will rotate hydroxyl group of residue A139S to optimize hbond
We optimize side chain of residue A139S
We optimize side chain of residue A140L
We will flip residue A141N to optimize hbond
We optimize side chain of residue A141N
We optimize side chain of residue A142V
We optimize side chain of residue A143D
We will flip residue A145Q to optimize hbond
We optimize side chain of residue A145Q
We optimize side chain of residue A146P
We optimize side chain of residue A147I
We optimize side chain of residue A148F
We will flip residue A150N to optimize hbond
We optimize side chain of residue A150N
We optimize side chain of residue A151I
We will rotate hydroxyl group of residue A152T to optimize hbond
We optimize side chain of residue A152T
We optimize side chain of residue A153L
We optimize side chain of residue A154P
We optimize side chain of residue A155V
We will rotate hydroxyl group of residue A156Y to optimize hbond
We optimize side chain of residue A156Y
We will rotate hydroxyl group of residue A157T to optimize hbond
We optimize side chain of residue A157T
We optimize side chain of residue A158L
We optimize side chain of residue A159K
We optimize side chain of residue A160E
We optimize side chain of residue A161R
We optimize side chain of residue A163L
We will flip residue A164Q to optimize hbond
We optimize side chain of residue A164Q
We optimize side chain of residue A165V
We optimize side chain of residue A166V
We optimize side chain of residue A167R
We will rotate hydroxyl group of residue A168S to optimize hbond
We optimize side chain of residue A168S
We optimize side chain of residue A169L
We optimize side chain of residue A170V
We optimize side chain of residue A171K
We optimize side chain of residue A172P
We optimize side chain of residue A173E
We will flip residue A174N to optimize hbond
We optimize side chain of residue A174N
We will rotate hydroxyl group of residue A175Y to optimize hbond
We optimize side chain of residue A175Y
We optimize side chain of residue A176R
We optimize side chain of residue A177R
We optimize side chain of residue A178L
We optimize side chain of residue A179D
We optimize side chain of residue A180I
We optimize side chain of residue A181V
We optimize side chain of residue A182R
We will rotate hydroxyl group of residue A183S to optimize hbond
We optimize side chain of residue A183S
We optimize side chain of residue A184L
We will rotate hydroxyl group of residue A185Y to optimize hbond
We optimize side chain of residue A185Y
We optimize side chain of residue A186E
We optimize side chain of residue A187D
We optimize side chain of residue A188L
We optimize side chain of residue A189E
We optimize side chain of residue A190D
We will flip residue A191H to optimize hbond
We optimize side chain of residue A191H
We optimize side chain of residue A192P
We will flip residue A193N to optimize hbond
We optimize side chain of residue A193N
We optimize side chain of residue A194V
We will flip residue A195Q to optimize hbond
We optimize side chain of residue A195Q
We optimize side chain of residue A196K
We optimize side chain of residue A197D
We optimize side chain of residue A198L
We optimize side chain of residue A199E
We optimize side chain of residue A200R
We optimize side chain of residue A201L
We will rotate hydroxyl group of residue A202T to optimize hbond
We optimize side chain of residue A202T
We will flip residue A203Q to optimize hbond
We optimize side chain of residue A203Q
We optimize side chain of residue A204E
We optimize side chain of residue A205R
We optimize side chain of residue A206I
We will flip residue A208H to optimize hbond
We optimize side chain of residue A208H
Time spent: 0.371062

,pdb_path,target,ligand,ligand_path
0,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M90_CA,J91_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
1,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M91_CA,J97_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
2,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M92_CA,J8V_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
3,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M93_CA,J8Y_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
4,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,7AFW_A,R9Q_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
5,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,7UWO_AB,WHL_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
6,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,7ZRB_A,JKI_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
7,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EI9_C,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
8,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EIA_AC,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
9,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EIB_AC,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
10,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EIC_AC,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
11,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8RU4_A,GLC_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
12,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSM_A,O2D_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
13,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSN_B,O2J_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
14,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSO_A,O2M_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
15,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSP_A,LVV_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
16,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSQ_B,HR5_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
17,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSR_B,NU4_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
18,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSS_A,O2P_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
19,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QST_AC,O3A_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
20,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSU_AC,O3D_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
21,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSV_D,O3G_D,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
22,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSW_AC,O3J_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
23,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSX_CB,O3M_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
24,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSY_B,K0J_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
25,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSZ_A,K3J_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
26,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8VLB_A,3JF_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...

In [11]:
# Add CRBN-pomalidomide structure as well:
pdb_id = "6H0F"
protein_chain = "B"
ligand_chain = "B"
ligand_code = "Y70"

rows.append(prepare_input_structures(pdb_id, protein_chain, ligand_chain, ligand_code, input_dir, evoef2_bin))

df_preprocess = pd.DataFrame(rows)
df_preprocess

############################################################################################
                                    EvoEF2
  A framework for macromolecular modeling, e.g.,protein design, protein side-chain packing,
protein structure energy minimization, add and optimize hydrogen bonds, build mutant model,
calculate protein folding stability, calculate protein-protein binding free energy, etc


  Copyright (c) Xiaoqiang Huang (xiaoqiah@umich.edu; tommyhuangthu@foxmail.com)
  Dept. of Computational Medicine & Bioinformatics
  Medical School
  University of Michigan
############################################################################################
command RepairStructure works
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue B70ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD on residue B70ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom NE on residue B70ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CZ on residue B70ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom NH1 on residue B70ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom NH2 on residue B70ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue B215ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD on residue B215ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom NE on residue B215ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CZ on residue B215ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom NH1 on residue B215ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom NH2 on residue B215ARG is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue B430GLU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD on residue B430GLU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OE1 on residue B430GLU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OE2 on residue B430GLU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue B431ASP is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OD1 on residue B431ASP is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OD2 on residue B431ASP is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue B432GLU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD on residue B432GLU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OE1 on residue B432GLU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OE2 on residue B432GLU is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG2 on residue B433ILE is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG1 on residue B433ILE is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD on residue B433ILE is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OG on residue B434SER is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue B436ASP is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OD1 on residue B436ASP is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom OD2 on residue B436ASP is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG on residue B437LYS is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CD on residue B437LYS is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CE on residue B437LYS is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom NZ on residue B437LYS is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG1 on residue B438VAL is invalid
Warning: in file src/Residue.cpp function ResidueCheckAtomCoordinateValidity line 799, the coordinate of sidechain atom CG2 on residue B438VAL is invalid
EvoEF Repairing PDB: optimization cycle 1 ...
We optimize side chain of residue B70R
We will rotate hydroxyl group of residue B71T to optimize hbond
We optimize side chain of residue B71T
We optimize side chain of residue B72L
We will flip residue B73H to optimize hbond
We optimize side chain of residue B73H
We optimize side chain of residue B74D
We optimize side chain of residue B75D
We optimize side chain of residue B76D
We will rotate hydroxyl group of residue B77S to optimize hbond
We optimize side chain of residue B77S
We will flip residue B79Q to optimize hbond
We optimize side chain of residue B79Q
We optimize side chain of residue B80V
We optimize side chain of residue B81I
We optimize side chain of residue B82P
We optimize side chain of residue B83V
We optimize side chain of residue B84L
We optimize side chain of residue B85P
We will flip residue B86Q to optimize hbond
We optimize side chain of residue B86Q
We optimize side chain of residue B87V
We optimize side chain of residue B88M
We optimize side chain of residue B89M
We optimize side chain of residue B90I
We optimize side chain of residue B91L
We optimize side chain of residue B92I
We optimize side chain of residue B93P
We will flip residue B95Q to optimize hbond
We optimize side chain of residue B95Q
We will rotate hydroxyl group of residue B96T to optimize hbond
We optimize side chain of residue B96T
We optimize side chain of residue B97L
We optimize side chain of residue B98P
We optimize side chain of residue B99L
We will flip residue B100Q to optimize hbond
We optimize side chain of residue B100Q
We optimize side chain of residue B101L
We optimize side chain of residue B102F
We will flip residue B103H to optimize hbond
We optimize side chain of residue B103H
We optimize side chain of residue B104P
We will flip residue B105Q to optimize hbond
We optimize side chain of residue B105Q
We optimize side chain of residue B106E
We optimize side chain of residue B107V
We will rotate hydroxyl group of residue B108S to optimize hbond
We optimize side chain of residue B108S
We optimize side chain of residue B109M
We optimize side chain of residue B110V
We optimize side chain of residue B111R
We will flip residue B112N to optimize hbond
We optimize side chain of residue B112N
We optimize side chain of residue B113L
We optimize side chain of residue B114I
We will flip residue B115Q to optimize hbond
We optimize side chain of residue B115Q
We optimize side chain of residue B116K
We optimize side chain of residue B117D
We optimize side chain of residue B118R
We will rotate hydroxyl group of residue B119T to optimize hbond
We optimize side chain of residue B119T
We optimize side chain of residue B120F
We optimize side chain of residue B122V
We optimize side chain of residue B123L
We will rotate hydroxyl group of residue B125Y to optimize hbond
We optimize side chain of residue B125Y
We will rotate hydroxyl group of residue B126S to optimize hbond
We optimize side chain of residue B126S
We will flip residue B127N to optimize hbond
We optimize side chain of residue B127N
We optimize side chain of residue B128V
We will flip residue B129Q to optimize hbond
We optimize side chain of residue B129Q
We optimize side chain of residue B130E
We optimize side chain of residue B131R
We optimize side chain of residue B132E
We will flip residue B134Q to optimize hbond
We optimize side chain of residue B134Q
We optimize side chain of residue B135F
We will rotate hydroxyl group of residue B137T to optimize hbond
We optimize side chain of residue B137T
We will rotate hydroxyl group of residue B138T to optimize hbond
We optimize side chain of residue B138T
We optimize side chain of residue B140E
We optimize side chain of residue B141I
We will rotate hydroxyl group of residue B142Y to optimize hbond
We optimize side chain of residue B142Y
We will rotate hydroxyl group of residue B144Y to optimize hbond
We optimize side chain of residue B144Y
We optimize side chain of residue B145R
We optimize side chain of residue B146E
We optimize side chain of residue B147E
We will flip residue B148Q to optimize hbond
We optimize side chain of residue B148Q
We optimize side chain of residue B149D
We optimize side chain of residue B150F
We optimize side chain of residue B152I
We optimize side chain of residue B153E
We optimize side chain of residue B154I
We optimize side chain of residue B155V
We optimize side chain of residue B156K
We optimize side chain of residue B157V
We optimize side chain of residue B158K
We optimize side chain of residue B160I
We optimize side chain of residue B162R
We will flip residue B163Q to optimize hbond
We optimize side chain of residue B163Q
We optimize side chain of residue B164R
We optimize side chain of residue B165F
We optimize side chain of residue B166K
We optimize side chain of residue B167V
We optimize side chain of residue B168L
We optimize side chain of residue B169E
We optimize side chain of residue B170L
We optimize side chain of residue B171R
We will rotate hydroxyl group of residue B172T to optimize hbond
We optimize side chain of residue B172T
We will flip residue B173Q to optimize hbond
We optimize side chain of residue B173Q
We will rotate hydroxyl group of residue B174S to optimize hbond
We optimize side chain of residue B174S
We optimize side chain of residue B175D
We optimize side chain of residue B177I
We will flip residue B178Q to optimize hbond
We optimize side chain of residue B178Q
We will flip residue B179Q to optimize hbond
We optimize side chain of residue B179Q
We optimize side chain of residue B181K
We optimize side chain of residue B182V
We will flip residue B183Q to optimize hbond
We optimize side chain of residue B183Q
We optimize side chain of residue B184I
We optimize side chain of residue B185L
We optimize side chain of residue B186P
We optimize side chain of residue B187E
We optimize side chain of residue B189V
We optimize side chain of residue B190L
We optimize side chain of residue B191P
We will rotate hydroxyl group of residue B192S to optimize hbond
We optimize side chain of residue B192S
We will rotate hydroxyl group of residue B193T to optimize hbond
We optimize side chain of residue B193T
We optimize side chain of residue B194M
We will rotate hydroxyl group of residue B195S to optimize hbond
We optimize side chain of residue B195S
We optimize side chain of residue B197V
We will flip residue B198Q to optimize hbond
We optimize side chain of residue B198Q
We optimize side chain of residue B199L
We optimize side chain of residue B200E
We will rotate hydroxyl group of residue B201S to optimize hbond
We optimize side chain of residue B201S
We optimize side chain of residue B202L
We will flip residue B203N to optimize hbond
We optimize side chain of residue B203N
We optimize side chain of residue B204K
We will flip residue B206Q to optimize hbond
We optimize side chain of residue B206Q
We optimize side chain of residue B207I
We optimize side chain of residue B208F
We optimize side chain of residue B209P
We will rotate hydroxyl group of residue B210S to optimize hbond
We optimize side chain of residue B210S
We optimize side chain of residue B211K
We optimize side chain of residue B212P
We optimize side chain of residue B213V
We will rotate hydroxyl group of residue B214S to optimize hbond
We optimize side chain of residue B214S
We optimize side chain of residue B215R
We optimize side chain of residue B216E
We optimize side chain of residue B217D
We will flip residue B218Q to optimize hbond
We optimize side chain of residue B218Q
We will rotate hydroxyl group of residue B220S to optimize hbond
We optimize side chain of residue B220S
We will rotate hydroxyl group of residue B221Y to optimize hbond
We optimize side chain of residue B221Y
We optimize side chain of residue B222K
We optimize side chain of residue B223W
We optimize side chain of residue B224W
We will flip residue B225Q to optimize hbond
We optimize side chain of residue B225Q
We optimize side chain of residue B226K
We will rotate hydroxyl group of residue B227Y to optimize hbond
We optimize side chain of residue B227Y
We will flip residue B228Q to optimize hbond
We optimize side chain of residue B228Q
We optimize side chain of residue B229K
We optimize side chain of residue B230R
We optimize side chain of residue B231K
We optimize side chain of residue B232F
We will flip residue B233H to optimize hbond
We optimize side chain of residue B233H
We will flip residue B236N to optimize hbond
We optimize side chain of residue B236N
We optimize side chain of residue B237L
We will rotate hydroxyl group of residue B238T to optimize hbond
We optimize side chain of residue B238T
We will rotate hydroxyl group of residue B239S to optimize hbond
We optimize side chain of residue B239S
We optimize side chain of residue B240W
We optimize side chain of residue B241P
We optimize side chain of residue B242R
We optimize side chain of residue B243W
We optimize side chain of residue B244L
We will rotate hydroxyl group of residue B245Y to optimize hbond
We optimize side chain of residue B245Y
We will rotate hydroxyl group of residue B246S to optimize hbond
We optimize side chain of residue B246S
We optimize side chain of residue B247L
We will rotate hydroxyl group of residue B248Y to optimize hbond
We optimize side chain of residue B248Y
We optimize side chain of residue B249D
We optimize side chain of residue B251E
We will rotate hydroxyl group of residue B252T to optimize hbond
We optimize side chain of residue B252T
We optimize side chain of residue B253L
We optimize side chain of residue B254M
We optimize side chain of residue B255D
We optimize side chain of residue B256R
We optimize side chain of residue B257I
We optimize side chain of residue B258K
We optimize side chain of residue B259K
We will flip residue B260Q to optimize hbond
We optimize side chain of residue B260Q
We optimize side chain of residue B261L
We optimize side chain of residue B262R
We optimize side chain of residue B263E
We optimize side chain of residue B264W
We optimize side chain of residue B265D
We optimize side chain of residue B266E
We will flip residue B267N to optimize hbond
We optimize side chain of residue B267N
We optimize side chain of residue B268L
We optimize side chain of residue B269K
We optimize side chain of residue B270D
We optimize side chain of residue B271D
We will rotate hydroxyl group of residue B272S to optimize hbond
We optimize side chain of residue B272S
We optimize side chain of residue B273L
We optimize side chain of residue B274P
We will rotate hydroxyl group of residue B275S to optimize hbond
We optimize side chain of residue B275S
We will flip residue B276N to optimize hbond
We optimize side chain of residue B276N
We optimize side chain of residue B277P
We optimize side chain of residue B278I
We optimize side chain of residue B279D
We optimize side chain of residue B280F
We will rotate hydroxyl group of residue B281S to optimize hbond
We optimize side chain of residue B281S
We will rotate hydroxyl group of residue B282Y to optimize hbond
We optimize side chain of residue B282Y
We optimize side chain of residue B283R
We optimize side chain of residue B284V
We optimize side chain of residue B288L
We optimize side chain of residue B289P
We optimize side chain of residue B290I
We optimize side chain of residue B291D
We optimize side chain of residue B292D
We optimize side chain of residue B293V
We optimize side chain of residue B294L
We optimize side chain of residue B295R
We optimize side chain of residue B296I
We will flip residue B297Q to optimize hbond
We optimize side chain of residue B297Q
We optimize side chain of residue B298L
We optimize side chain of residue B299L
We optimize side chain of residue B300K
We optimize side chain of residue B301I
We will rotate hydroxyl group of residue B303S to optimize hbond
We optimize side chain of residue B303S
We optimize side chain of residue B305I
We will flip residue B306Q to optimize hbond
We optimize side chain of residue B306Q
We optimize side chain of residue B307R
We optimize side chain of residue B308L
We optimize side chain of residue B309R
We optimize side chain of residue B311E
We optimize side chain of residue B312L
We optimize side chain of residue B313D
We optimize side chain of residue B314I
We optimize side chain of residue B315M
We will flip residue B316N to optimize hbond
We optimize side chain of residue B316N
We optimize side chain of residue B317K
We will rotate hydroxyl group of residue B319T to optimize hbond
We optimize side chain of residue B319T
We will rotate hydroxyl group of residue B320S to optimize hbond
We optimize side chain of residue B320S
We optimize side chain of residue B321L
We optimize side chain of residue B324K
We will flip residue B325Q to optimize hbond
We optimize side chain of residue B325Q
We will flip residue B327Q to optimize hbond
We optimize side chain of residue B327Q
We optimize side chain of residue B328E
We will rotate hydroxyl group of residue B329T to optimize hbond
We optimize side chain of residue B329T
We optimize side chain of residue B330E
We optimize side chain of residue B331I
We will rotate hydroxyl group of residue B332T to optimize hbond
We optimize side chain of residue B332T
We will rotate hydroxyl group of residue B333T to optimize hbond
We optimize side chain of residue B333T
We optimize side chain of residue B334K
We will flip residue B335N to optimize hbond
We optimize side chain of residue B335N
We optimize side chain of residue B336E
We optimize side chain of residue B337I
We optimize side chain of residue B338F
We will rotate hydroxyl group of residue B339S to optimize hbond
We optimize side chain of residue B339S
We optimize side chain of residue B340L

,pdb_path,target,ligand,ligand_path
0,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M90_CA,J91_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
1,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M91_CA,J97_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
2,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M92_CA,J8V_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
3,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6M93_CA,J8Y_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
4,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,7AFW_A,R9Q_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
5,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,7UWO_AB,WHL_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
6,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,7ZRB_A,JKI_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
7,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EI9_C,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
8,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EIA_AC,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
9,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EIB_AC,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
10,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8EIC_AC,WHL_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
11,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8RU4_A,GLC_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
12,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSM_A,O2D_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
13,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSN_B,O2J_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
14,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSO_A,O2M_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
15,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSP_A,LVV_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
16,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSQ_B,HR5_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
17,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSR_B,NU4_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
18,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSS_A,O2P_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
19,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QST_AC,O3A_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
20,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSU_AC,O3D_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
21,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSV_D,O3G_D,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
22,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSW_AC,O3J_C,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
23,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSX_CB,O3M_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
24,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSY_B,K0J_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
25,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,5QSZ_A,K3J_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
26,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,8VLB_A,3JF_A,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...
27,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...,6H0F_B,Y70_B,/scratch/ymeng/NNeosurf/masif-neosurf/data/inp...

In [24]:
# Write df_preprocess to input_manifest.csv, then run preprocess_array.sh
df_preprocess.to_csv(input_manifest, index=False)
n_rows = len(df_preprocess)
manifest_abs = os.path.abspath(input_manifest)
# Use {var} for Python values in ! commands — ${var} becomes a literal '$' + path in Jupyter
!sbatch --array=1-{n_rows} scripts/slurm/preprocess_array.sh {manifest_abs}

sbatch: [ESTIMATION] The estimated cost of this job is CHF 0.05
sbatch: ╭──────────────────────────────┬─────────────┬─────────────┬─────────────╮
sbatch: │ [in CHF]                     │ Capping     │ Consumed    │ Queued ¹⁾ ²⁾│
sbatch: ├──────────────────────────────┼─────────────┼─────────────┼─────────────┤
sbatch: │ username : ymeng             │ 0           │ 1.25        │ 0.1         │
sbatch: ├──────────────────────────────┼─────────────┼─────────────┼─────────────┤
sbatch: │ account : upthomae           │ 10,000      │ 1.45        │ 0.1         │
sbatch: ╰──────────────────────────────┴─────────────┴─────────────┴─────────────╯
sbatch: ¹⁾ Estimated cost of the queued jobs and this job
sbatch: ²⁾ Queued jobs costs are based on its walltime (option --time)
Submitted batch job 54908372

___
### Step 2 - Run masif_search around ligand residues
1. Query with VHL structure as target, search for seed patches around the seed ligands

In [26]:
import numpy as np
from Bio.PDB import PDBParser

QUERY_TARGET = "8VLB_A"
query_out_dir = os.path.join(masif_search_out_dir, QUERY_TARGET)
os.makedirs(query_out_dir, exist_ok=True)

search_manifest = os.path.join(query_out_dir, "search_manifest.csv")


def parse_ligand_name(ligand):
    code, chain = ligand.rsplit("_", 1)
    return code.strip(), chain.strip()


def protein_chain_from_target(target, ligand_chain):
    _, chains = target.split("_", 1)
    if chains == ligand_chain:
        return ligand_chain
    if chains.endswith(ligand_chain):
        protein = chains[: -len(ligand_chain)]
        if protein:
            return protein
    raise ValueError(f"Cannot infer protein chain from {target=} {ligand_chain=}")


def ligand_anchor_from_row(row):
    """Return (ligand_chain, ligand_resid) from pdb_path and ligand column."""
    ligand_code, ligand_chain = parse_ligand_name(row["ligand"])
    structure = PDBParser(QUIET=True).get_structure(row["target"], row["pdb_path"])
    residues = [
        r
        for r in structure[0][ligand_chain].get_residues()
        if r.get_resname().strip() == ligand_code
    ]
    if not residues:
        raise ValueError(f"No {ligand_code} on chain {ligand_chain} in {row['pdb_path']}")
    if len(residues) == 1:
        return ligand_chain, int(residues[0].id[1])

    protein_chain = protein_chain_from_target(row["target"], ligand_chain)
    ref = np.mean(
        [r["CA"].get_coord() for r in structure[0][protein_chain].get_residues() if r.id[0] == " " and "CA" in r],
        axis=0,
    )
    best = min(
        residues,
        key=lambda r: np.linalg.norm(
            np.mean([a.get_coord() for a in r.get_atoms() if a.element != "H"], axis=0) - ref
        ),
    )
    return ligand_chain, int(best.id[1])


query_row = df_preprocess.loc[df_preprocess["target"] == QUERY_TARGET].iloc[0]
target_chain, target_resid = ligand_anchor_from_row(query_row)

search_rows = []
for _, seed_row in df_preprocess[df_preprocess["target"] != QUERY_TARGET].iterrows():
    seed_chain, seed_resid = ligand_anchor_from_row(seed_row)
    out_dir = query_out_dir
    search_rows.append(
        {
            "query_target": QUERY_TARGET,
            "target_chain": target_chain,
            "target_resid": target_resid,
            "seed_target": seed_row["target"],
            "seed_chain": seed_chain,
            "seed_resid": seed_resid,
            "out_dir": out_dir,
        }
    )

df_search = pd.DataFrame(search_rows)
df_search.to_csv(search_manifest, index=False)
print(f"Query {QUERY_TARGET}: chain={target_chain} resid={target_resid}")
print(f"Wrote {len(df_search)} search jobs to {search_manifest}")
df_search.head()

Query 8VLB_A: chain=A resid=301
Wrote 27 search jobs to /scratch/ymeng/NNeosurf/masif-neosurf/data/masif_search/8VLB_A/search_manifest.csv

,query_target,target_chain,target_resid,seed_target,seed_chain,seed_resid,out_dir
0,8VLB_A,A,301,6M90_CA,A,601,/scratch/ymeng/NNeosurf/masif-neosurf/data/mas...
1,8VLB_A,A,301,6M91_CA,A,601,/scratch/ymeng/NNeosurf/masif-neosurf/data/mas...
2,8VLB_A,A,301,6M92_CA,A,601,/scratch/ymeng/NNeosurf/masif-neosurf/data/mas...
3,8VLB_A,A,301,6M93_CA,A,601,/scratch/ymeng/NNeosurf/masif-neosurf/data/mas...
4,8VLB_A,A,301,7AFW_A,A,401,/scratch/ymeng/NNeosurf/masif-neosurf/data/mas...

In [ ]:
n_search = len(df_search)
search_manifest_abs = os.path.abspath(search_manifest)
!sbatch --array=1-{n_search} scripts/slurm/search_array.sh {search_manifest_abs}

sbatch: [ESTIMATION] The estimated cost of this job is CHF 0.22
sbatch: ╭──────────────────────────────┬─────────────┬─────────────┬─────────────╮
sbatch: │ [in CHF]                     │ Capping     │ Consumed    │ Queued ¹⁾ ²⁾│
sbatch: ├──────────────────────────────┼─────────────┼─────────────┼─────────────┤
sbatch: │ username : ymeng             │ 0           │ 1.25        │ 0.25        │
sbatch: ├──────────────────────────────┼─────────────┼─────────────┼─────────────┤
sbatch: │ account : upthomae           │ 10,000      │ 1.45        │ 0.25        │
sbatch: ╰──────────────────────────────┴─────────────┴─────────────┴─────────────╯
sbatch: ¹⁾ Estimated cost of the queued jobs and this job
sbatch: ²⁾ Queued jobs costs are based on its walltime (option --time)
Submitted batch job 54909048

In [28]:
from pathlib import Path

import numpy as np


def parse_score_file(score_file):
    """Parse MaSIF comma-separated score summary (see process_search_outputs.py)."""
    score_file = Path(score_file)
    if not score_file.is_file():
        return None
    with score_file.open() as f:
        return {part.split(": ")[0]: part.split(": ")[1] for part in f.read().split(", ")}


def gather_search_results(results_root, query_target):
    """Collect .score fields and 4x4 transforms under results_root/query_target/site_*."""
    target_dir = Path(results_root) / query_target
    if not target_dir.is_dir():
        raise FileNotFoundError(f"No search output directory: {target_dir}")

    rows = []
    for site_dir in sorted(target_dir.glob("site_*")):
        target_info = parse_score_file(site_dir / "target_info.txt")
        target_vix = int(target_info["vix"]) if target_info and "vix" in target_info else None

        for score_path in sorted(site_dir.glob("*/*.score")):
            summary = parse_score_file(score_path)
            if summary is None:
                continue

            transform_path = score_path.with_name(f"{score_path.stem}_transform.npy")
            if not transform_path.is_file():
                continue

            transform = np.load(transform_path)
            if transform.shape != (4, 4):
                print(f"Skipping invalid transform shape {transform.shape}: {transform_path}")
                continue

            rows.append(
                {
                    "target": query_target,
                    "target_site": site_dir.name,
                    "target_vix": target_vix,
                    "matched_protein": summary["name"],
                    "matched_patch_id": int(summary["point id"]),
                    "score": float(summary["score"]),
                    "desc_dist_score": float(summary["desc_dist_score"]),
                    "clashing_ca": int(summary["clashing_ca"]),
                    "clashing_heavy": int(summary["clashing_heavy"]),
                    "matched_vix": int(summary["match_vix"])
                    if "match_vix" in summary
                    else None,
                    "desc_dist": float(summary["desc_dist"])
                    if "desc_dist" in summary
                    else None,
                    "iface_score": float(summary["iface_score"])
                    if "iface_score" in summary
                    else None,
                    "mean_desc_dist_score": float(summary["mean_desc_dist_score"])
                    if "mean_desc_dist_score" in summary
                    else None,
                    "flattened_transform": ",".join(map(str, transform.flatten())),
                }
            )

    return pd.DataFrame(rows)


results_csv = os.path.join(query_out_dir, f"{QUERY_TARGET}_search_results.csv")
df_results = gather_search_results(query_out_dir, QUERY_TARGET)
df_results.to_csv(results_csv, index=False)
print(f"Wrote {len(df_results)} matches to {results_csv}")
df_results.head()

Wrote 5 matches to /scratch/ymeng/NNeosurf/masif-neosurf/data/masif_search/8VLB_A/8VLB_A_search_results.csv

,target,target_site,target_vix,matched_protein,matched_patch_id,score,desc_dist_score,clashing_ca,clashing_heavy,matched_vix,desc_dist,iface_score,mean_desc_dist_score,flattened_transform
0,8VLB_A,site_10,1151,5QSO_A,0,0.9207,20.208859,0,3,2970,1.860577,0.368014,0.132084,"0.1891158143360388,-0.5745362750716273,0.79633..."
1,8VLB_A,site_22,876,7UWO_AB,0,0.9724,10.627931,0,0,3781,1.983913,0.418113,0.100263,"0.8372511317894467,-0.3670006845399405,0.40536..."
2,8VLB_A,site_32,3051,5QSV_D,13,0.9433,20.194905,0,2,5576,1.900894,0.559067,0.160277,"0.8865497883281478,0.40543432257998213,-0.2228..."
3,8VLB_A,site_32,3051,5QSV_D,5,0.9466,20.453185,0,4,2937,1.946821,0.617374,0.159791,"0.8761196444031263,0.31449496918257425,-0.3653..."
4,8VLB_A,site_4,440,6H0F_B,7,0.9111,23.760661,0,0,4092,1.965906,0.866648,0.204833,"0.6092110780241586,-0.4468527467828541,0.65512..."