## Notebook to split all liganded human PDB into target/seed

Split all human liganded pdb into:
- target: ligase+glue complex (e.g. VHL, CRBN)
- seed: database of any liganded human PDB structure

### Input:
- `human_reference_proteome_pdb_ligands.csv` from git@github.com:meng-yx/ligand_viewer.git repo

In [5]:
import os
import pandas as pd
from pathlib import Path

repo_root = !git rev-parse --show-toplevel
repo_root = repo_root[0]
os.chdir(repo_root)

data_dir = Path(repo_root) / "data/human_reference_proteome_liganded_pdbs"
os.makedirs(data_dir, exist_ok=True)

# ----- Input ------
human_ref_proteome_dir = Path("/work/upthomae/Meng/ligand_viewer/data/human_reference_proteome/")
all_ligands_csv = os.path.join(human_ref_proteome_dir, "human_reference_proteome_pdb_ligands.csv")

# ----- Output ------
all_ligands_split_csv = os.path.join(data_dir, "human_reference_proteome_pdb_ligands_split.csv")

In [2]:
df_all_ligands = pd.read_csv(all_ligands_csv)

df_all_ligands.head()

,uniprot_id,gene_name,recommendedName,pdb_id,protein_chain,ligand_chain,ligand_code,ligand_name,smiles,percent_intracellular,formula,mw,qed,num_carbon,num_N_O,uniprot_id_count
0,A1L3X0,ELOVL7,Very long chain fatty acid elongase 7,6Y7F,A,A,OFN,"~{S}-[2-[3-[[(2~{R})-4-[[[(2~{R},3~{S},4~{R},5...",CCCCCCCCCCCCCCCCCC(=O)CC(=O)SCCNC(=O)CCNC(=O)[...,0.213523,C41H72N7O18P3S,1075.386739,0.024703,41.0,25.0,1.0
1,A1L3X0,ELOVL7,Very long chain fatty acid elongase 7,6Y7F,A,A,37X,Octyl Glucose Neopentyl Glycol,CCCCCCC(CCCCCC)(CO[C@@H]1[C@H]([C@@H]([C@H]([C...,0.213523,C27H52O12,568.345877,0.099222,27.0,12.0,3.0
2,A0FGR8,ESYT2,Extended synaptotagmin-2,4P42,A,A,EGC,"2-(2-{2-[2-(2-{2-[2-(2-{2-[4-(1,1,3,3-TETRAMET...",CC(C)(C)CC(C)(C)c1ccc(cc1)OCCOCCOCCOCCOCCOCCOC...,1.000000,C32H58O10,602.402998,0.135862,32.0,10.0,1.0
3,A4D1P6,WDR91,WD repeat-containing protein 91,8SHJ,A,A,ZI8,N-[3-(4-chlorophenyl)oxetan-3-yl]-4-[(3S)-3-hy...,c1cc(ccc1C(=O)NC2(COC2)c3ccc(cc3)Cl)N4CC[C@@H]...,1.000000,C20H21ClN2O3,372.124070,0.865528,20.0,5.0,1.0
4,A4D1P6,WDR91,WD repeat-containing protein 91,8T55,C,C,ZI3,N-[3-(4-chlorophenyl)oxetan-3-yl]-1-propanoyl-...,CCC(=O)N1CCCc2c1cccc2C(=O)NC3(COC3)c4ccc(cc4)Cl,1.000000,C22H23ClN2O3,398.139720,0.854092,22.0,5.0,1.0

In [6]:
# List of known glueable ligases
uniprot_ligases = [
    "Q96SW2", # CRBN
    "P40337", # VHL
    "Q66K64", # DCAF15
    "P41182", # BCL6
    "Q9Y297", # FBW1A
    "Q9NXF7", # DCAF16
    "P62942", # FKBP12 
    "Q9NVX7"  # KBTBD4
]

df_all_ligands["split"] = df_all_ligands["uniprot_id"].apply(lambda x: "target" if x in uniprot_ligases else "seed")

df_all_ligands.to_csv(all_ligands_split_csv, index=False)

df_all_ligands[df_all_ligands["split"] == "target"].head()

,uniprot_id,gene_name,recommendedName,pdb_id,protein_chain,ligand_chain,ligand_code,ligand_name,smiles,percent_intracellular,formula,mw,qed,num_carbon,num_N_O,uniprot_id_count,split
15003,P40337,VHL,von Hippel-Lindau disease tumor suppressor,3ZRC,F,F,L8B,(4R)-4-HYDROXY-1-[(3-METHYLISOXAZOL-5-YL)ACETY...,Cc1cc(on1)CC(=O)N2C[C@@H](C[C@H]2C(=O)NCc3ccc(...,1.0,C21H22N4O5,410.159020,0.630792,21.0,9.0,1.0,target
15004,P40337,VHL,von Hippel-Lindau disease tumor suppressor,3ZTC,L,L,TR0,(4R)-N-(BIPHENYL-4-YLMETHYL)-4-HYDROXY-1-[(3-M...,Cc1cc(on1)CC(=O)N2C[C@@H](C[C@H]2C(=O)NCc3ccc(...,1.0,C24H25N3O4,419.184506,0.640014,24.0,7.0,1.0,target
15005,P40337,VHL,von Hippel-Lindau disease tumor suppressor,3ZTD,C,C,ZTD,METHYL 4-[({(4R)-4-HYDROXY-1-[(3-METHYLISOXAZO...,Cc1cc(on1)CC(=O)N2C[C@@H](C[C@H]2C(=O)NCc3ccc(...,1.0,C20H23N3O6,401.158685,0.679488,20.0,9.0,1.0,target
15006,P40337,VHL,von Hippel-Lindau disease tumor suppressor,3ZUN,C,C,ZUN,"(4R)-4-hydroxy-1-[(3-methyl-1,2-oxazol-5-yl)ac...",Cc1cc(on1)CC(=O)N2C[C@@H](C[C@H]2C(=O)NCc3ccc(...,1.0,C18H20N4O6,388.138284,0.548708,18.0,10.0,1.0,target
15007,P40337,VHL,von Hippel-Lindau disease tumor suppressor,4AWJ,F,F,V6F,(4R)-1-acetyl-4-hydroxy-N-methyl-L-prolinamide,CC(=O)N1C[C@@H](C[C@H]1C(=O)NC)O,1.0,C8H14N2O3,186.100442,0.535294,8.0,5.0,1.0,target

In [ ]:
df_all_ligands[df_all_ligands["split"] == "seed"]

,uniprot_id,gene_name,recommendedName,pdb_id,protein_chain,ligand_chain,ligand_code,ligand_name,smiles,percent_intracellular,formula,mw,qed,num_carbon,num_N_O,uniprot_id_count,split
15003,P40337,VHL,von Hippel-Lindau disease tumor suppressor,3ZRC,F,F,L8B,(4R)-4-HYDROXY-1-[(3-METHYLISOXAZOL-5-YL)ACETY...,Cc1cc(on1)CC(=O)N2C[C@@H](C[C@H]2C(=O)NCc3ccc(...,1.0,C21H22N4O5,410.159020,0.630792,21.0,9.0,1.0,target
15004,P40337,VHL,von Hippel-Lindau disease tumor suppressor,3ZTC,L,L,TR0,(4R)-N-(BIPHENYL-4-YLMETHYL)-4-HYDROXY-1-[(3-M...,Cc1cc(on1)CC(=O)N2C[C@@H](C[C@H]2C(=O)NCc3ccc(...,1.0,C24H25N3O4,419.184506,0.640014,24.0,7.0,1.0,target
15005,P40337,VHL,von Hippel-Lindau disease tumor suppressor,3ZTD,C,C,ZTD,METHYL 4-[({(4R)-4-HYDROXY-1-[(3-METHYLISOXAZO...,Cc1cc(on1)CC(=O)N2C[C@@H](C[C@H]2C(=O)NCc3ccc(...,1.0,C20H23N3O6,401.158685,0.679488,20.0,9.0,1.0,target
15006,P40337,VHL,von Hippel-Lindau disease tumor suppressor,3ZUN,C,C,ZUN,"(4R)-4-hydroxy-1-[(3-methyl-1,2-oxazol-5-yl)ac...",Cc1cc(on1)CC(=O)N2C[C@@H](C[C@H]2C(=O)NCc3ccc(...,1.0,C18H20N4O6,388.138284,0.548708,18.0,10.0,1.0,target
15007,P40337,VHL,von Hippel-Lindau disease tumor suppressor,4AWJ,F,F,V6F,(4R)-1-acetyl-4-hydroxy-N-methyl-L-prolinamide,CC(=O)N1C[C@@H](C[C@H]1C(=O)NC)O,1.0,C8H14N2O3,186.100442,0.535294,8.0,5.0,1.0,target
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27137,Q9Y297,BTRC,F-box/WD repeat-containing protein 1A,6M91,A,A,J97,"3-({4-[(2,6-dichlorophenyl)sulfanyl]-2-oxo-6-(...",c1cc(cc(c1)NC(=O)C2=C(C=C(NC2=O)C(F)(F)F)Sc3c(...,1.0,C20H11Cl2F3N2O4S,501.976868,0.408829,20.0,6.0,2.0,target
27138,Q9Y297,BTRC,F-box/WD repeat-containing protein 1A,6M92,A,A,J8V,"3-{[2-oxo-4-phenoxy-6-(trifluoromethyl)-1,2-di...",c1ccc(cc1)OC2=C(C(=O)NC(=C2)C(F)(F)F)C(=O)Nc3c...,1.0,C20H13F3N2O5,418.077656,0.577285,20.0,7.0,2.0,target
27139,Q9Y297,BTRC,F-box/WD repeat-containing protein 1A,6M93,A,A,J8Y,2-oxo-N-[3-(1H-tetrazol-5-yl)phenyl]-6-(triflu...,c1cc(cc(c1)NC(=O)C2=CC=C(NC2=O)C(F)(F)F)c3[nH]...,1.0,C14H9F3N6O2,350.073908,0.666230,14.0,8.0,2.0,target
28128,Q9NXF7,DCAF16,DDB1- and CUL4-associated factor 16,8G46,B,B,YK3,"tert-butyl [(6S,10P)-4-{4-[(ethanesulfonyl)ami...",CCS(=O)(=O)Nc1ccc(cc1)C2=N[C@H](c3nnc(n3-c4c2c...,1.0,C25H31N5O4S2,529.181746,0.465295,25.0,9.0,2.0,target
28129,Q9NXF7,DCAF16,DDB1- and CUL4-associated factor 16,8OV6,B,C,U79,methyl 2-[(9~{S})-7-[4-[4-[[4-[(3-cyano-4-meth...,Cc1ccc(c2c1c(c[nH]2)C#N)NS(=O)(=O)c3ccc(cc3)CN...,1.0,C44H38N8O5S2,822.240658,0.116909,44.0,13.0,2.0,target